---
abstract: 'fast grid transformations'
author:
  - 'gray <gray@cpan.org>'
build_requires:
  Test::More: '0.82'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Grid-Transform
no_index:
  directory:
    - t
    - inc
requires:
  XSLoader: '0'
resources:
  repository: http://github.com/gray/grid-transform
version: '0.09'
